version: '3'

services:

  db:
    image: postgres
    volumes: 
     - /Users/adamwatt/myGoProjects/shortlyCF-GO/data:/data/db
    ports:
     - '5432:5432' 
  shortly-cf:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
     - '6060:6060' 
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
     